Tag every character
sukritsangvong/wp-browser-extension pull request #33
Opened 2023-01-17 06:06 UTC by RichartE

This pull request adds the following functionality:
- Adds html mark tags around every character in the wikipedia body-content
- Exposes a clean text that can be compared to find index matches
- Exposes API to mark index ranges
- Exposes API to remove all marks

This pull request also reorganizes the code a bit. There is now a root.js file where the methods are imported to reduce the code complexity. The goal is to have each logical area be in its own file and the root just connecting them all as needed.

2023-01-17 20:18 UTC, RichartE commented
you can import the authoritative html text from the tagEveryChar.js file. To highlight characters you need to use the markPage function (from the markPage.js file) that takes a start and end (inclusive) index matching the text. To clear the highlights use the removeMarks funciton from markPage.js file.

2023-01-17 21:07 UTC, sukritsangvong requested changes
I tried opening the United States page (https://en.wikipedia.org/wiki/United_States) and the page totally crashed on me. The Pasta page was also pretty so highlight the first sentence and remove it. Can you please make sure that this works on the United States page on your machine? If it does, then it's probably fine. My machine is kinda slow today. If it doesn't, you probably have to optimize something to make it faster.

2023-01-17 21:07 UTC, sukritsangvong commented on wikichange/src/content/content.js
> +    console.groupEnd();
do we need to keep these console.log()s?

2023-01-19 19:21 UTC, LuisaE commented on wikichange/src/content/content.js
> +    console.groupEnd();
Remove console.logs, it will further slow down the page

2023-01-19 19:22 UTC, LuisaE commented
Great! We just need to make sure this will not crash, so maybe merge without actually calling it? So I can start my part testing locally.

2023-01-19 19:23 UTC, LuisaE commented on wikichange/src/content/root.js
> +console.info(text.substring(0, 21));
Let's move this code to the readme, as it is test code and not actually "prod ready"

2023-01-19 19:24 UTC, LuisaE commented on wikichange/src/content/root.js
> +console.info(text.substring(0, 21));
Eg: ### How to tag every word

2023-01-19 20:02 UTC, sukritsangvong commented
Tested again and it crashed on the United States page the first couple of times then able to load on 3rd or 4th try. It froze after the first couple of words were highlighted in yellow and the loader was spinning. (the graph not showing up). This might be a combination of a couple of things. will take a deeper look into this.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/55929961/213547640-a6457323-5c41-449e-b619-d7a6d4c7413f.png">

2023-01-19 20:09 UTC, sukritsangvong commented on wikichange/src/content/compareRevisionService.js
>      divsWithNoInsOuts.forEach((x) => console.log(x.innerHTML));
I think this was left over from my pr, but can u please remove this line.

2023-01-19 20:13 UTC, sukritsangvong commented
Checked with the main, and the graph loading was slow, but it wasn't slow enough to cause the page to crash. There is probably something in this pr that is slowing this down to crossing the threshold.

2023-01-19 22:40 UTC, sukritsangvong reviewed
Everything looks good. Will have Luisa be the one to approve this since she will have to be working with this (want her to at least see them before merging). @LuisaE

2023-01-19 23:08 UTC, LuisaE approved these changes
Thank you, looks great!

2023-01-19 23:08 UTC, LuisaE commented on wikichange/src/content/tagEveryWord.js
> +                return NodeFilter.FILTER_REJECT;
Why do we need this and what do it do?

2023-01-19 23:08 UTC, LuisaE commented on wikichange/assets/content.css
> +mark{
Thanks for creating a css file, maybe when this is merged @ducndh can add all the CSS here?

2023-01-19 23:08 UTC, LuisaE commented
> Everything looks good. Will have Luisa be the one to approve this since she will have to be working with this (want her to at least see them before merging). @LuisaE

Approved!

2023-01-20 02:26 UTC, sukritsangvong approved these changes

2023-01-20 05:01 UTC, merged