updated-ticks
sukritsangvong/wp-browser-extension pull request #71
Opened 2023-02-07 18:10 UTC by shirin601

updated ticks. should probably merge the other PR for data decimation too!
<img width="989" alt="Screen Shot 2023-02-07 at 12 08 47 PM" src="https://user-images.githubusercontent.com/63482822/217330067-1a421b16-ebbc-4b8e-9218-e84cc17a0759.png">

2023-02-07 19:06 UTC, LuisaE requested changes
Quick style change

2023-02-07 19:06 UTC, LuisaE commented on wikichange/src/content/graph.js
> +                    },
Looks good, but can you indent this real quick? Otherwise approved

2023-02-13 03:05 UTC, RichartE approved these changes

2023-02-13 20:40 UTC, LuisaE commented
@shirin601 is this still active? If not, let's close it

2023-02-15 01:59 UTC, closed without merging