Add Options Page
sukritsangvong/wp-browser-extension pull request #81
Opened 2023-02-16 11:17 UTC by RichartE

Made it possible to customize the browser extension with a few options:
- Highlight (on or off)
- Invert highlight (yes or no)
- Choose a highlight color

Also, added link to options page from popup.

2023-02-16 15:13 UTC, LuisaE commented
Those are good ideas, but we would want to discuss it:
1. People are not clicking the popup, so no one will see a page linked from there.
2. Changing the color is great! However, inverting the highlight is confusing because 1. we don't change the text in the box; 2. What does it mean? It's unclear.
3. I feel strongly about this one: Turning off the highlight shouldn't be an available feature. We are Addition viewer so highlighting additions is a main feature, and generally, you turn off those - people are using it for a reason, and if they didn't want it they wouldn't install it. Keeping the highlight button that doesn't work when it is off is weird. 

TLTR: I think we should keep the color, but not on an extra page, in the popup.

@sukritsangvong @shirin601 @ducndh @etiennerichart

2023-02-16 16:29 UTC, shirin601 commented
I am not really sure the inversion would do? If you could elaborate, that would be great.

I agree with Luisa. Turning the highlight on and off should not be a feature -- people would not download it if they did not want to use it. Furthermore, through both iterations of the user study, no one has complained about the highlights being a hindrance while reading. So I do not think this feature would help/add anything.

Lastly, the color is interesting. One person in my user study told me that we should keep the highlight button and highlights in the same color so that users can subconsciously make the connection. That might be something to think about.

2023-02-16 17:01 UTC, sukritsangvong commented
^same comments as above

2023-02-16 17:08 UTC, sukritsangvong commented
Tested it out. Looks pretty good. 
- I would prefer that the options be on the popup extension rather than on a separate page. 
- Not 100% sure what the purpose of the `Invert Highlight` is. 
- When disabling the highlights, I would expect to have something on the page saying that the highlight has been disabled, else it is a bit confusing to see that there is X number of changes but nothing was highlighted. Because of this, we should either make it clear that the highlight is turned off on the page or remove it.

2023-02-18 21:55 UTC, sukritsangvong commented
I think the highlight is broken. Nothing changes when I click the highlight button.

2023-02-19 01:05 UTC, RichartE commented
I see the highlights changing on my computer, is anyone else getting the same issue?

2023-02-19 01:11 UTC, sukritsangvong commented
Maybe it has something to do with what @LuisaE mentioned in discord. I just saw that when I am on your branch, I am for some reason several commits behind and there is a huge merge conflict when I tried to pull (I didn't change anything from your branch). Might be something to do with force push (I normally just merge main into my branch when I want to update my branch. Force push tends to act weird, so I never use them)

Will try to resolve this and see if I still get the problem.

2023-02-19 01:21 UTC, sukritsangvong commented
Okay, now I see all the changes you made. I think it was something trippy with the force push. I manually checked out to the latest commit you made. We should merge the color option into the main, but we should remove the limitation from this pr and put it into a new pr. We should merge the limitation thingy when we actually do have the limitation page. Having the "go to limitation page" in the main that doesn't get us anywhere seems weird.

I will approve after the limitation thingy is moved to a new pr.

2023-02-19 01:29 UTC, LuisaE requested changes
Small formating changes, other than that good to go, thank you!

2023-02-19 01:29 UTC, LuisaE commented on wikichange/assets/content.css
> +  }
Cool, thank you for cleaning it up!

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/content/content.js
> +            } and the present day. Some of the changes were purely formatting or deletions and, therefore, are not highlighted. Visit our <a href="">limitations</a> page to learn more.`;
Let's remove the limitations for now

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/content/markPageChar.js
> +    if(toMark.length > 3000){
Can you add space between if ( and for (?

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/content/markPageWord.js
> +    if(toMark.length > 3000){
Same here

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/options/options.js
> +// Saves options to chrome.storage
Can you change to the /** comments? So we keep everything the same

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/options/options.js
> +// Restores select box and checkbox state using the preferences
Same here /**

2023-02-19 01:29 UTC, LuisaE commented on wikichange/src/popup/popup.html
> +          <a role="button" href="" id="options">Extension Options</a>
Maybe center year too? It's a little bit weird as it is to have one at the center and another one being a bullet

2023-02-19 03:18 UTC, sukritsangvong approved these changes
lgtm @LuisaE

2023-02-20 20:07 UTC, LuisaE approved these changes

2023-02-20 20:07 UTC, LuisaE commented on wikichange/src/content/content.js
> +            } and the present day.`;
We want to keep "Some of the changes were purely formatting or deletions and, therefore, are not highlighted.". The rest looks good, thanks

2023-02-21 01:52 UTC, merged