adjust options
sukritsangvong/wp-browser-extension pull request #90
Opened 2023-02-24 17:37 UTC by RichartE

2023-02-24 22:15 UTC, sukritsangvong approved these changes

2023-02-25 18:34 UTC, LuisaE commented
@sukritsangvong @etiennerichart  Sorry, but what is this? I thought the reset color was already merged. And we can't merge as we are past the code freeze.

2023-02-25 18:36 UTC, sukritsangvong commented
> @sukritsangvong @etiennerichart Sorry, but what is this? I thought the reset color was already merged. And we can't merge as we are past the code freeze.

@RichartE changed the position of the button and reformat the style of the code. no functionality changes. if we are strict about the code freeze, we don't have to merge this.

2023-02-25 18:37 UTC, sukritsangvong requested changes
blocking changes for now

2023-02-27 03:32 UTC, closed without merging